export const themes = [
  {
    name: 'cyan',
    label: 'Pirate',
    colors: { bg: '#C7E0DD', fg: '#0146E6', fg_secondary: '#084164' },
    dark: false,
    contrast: 5.01,
    aa: 'AA',
  },
  {
    name: 'cyan',
    label: 'Harbor',
    colors: { bg: '#2A1E54', fg: '#E5ECC7', fg_secondary: '#BBD5E6' },
    dark: true,
    contrast: 12.14,
    aa: 'AAA',
  },
  {
    name: 'pink',
    label: 'Peach',
    colors: { bg: '#EED9D6', fg: '#0C54B2', fg_secondary: '#2D1E49' },
    dark: false,
    contrast: 5.3,
    aa: 'AA',
  },
  {
    name: 'pink',
    label: 'Dizzy',
    colors: { bg: '#562039', fg: '#E9B55C', fg_secondary: '#E2DBEE' },
    dark: true,
    contrast: 6.75,
    aa: 'AA',
  },
  {
    name: 'sands',
    label: 'Quiet',
    colors: { bg: '#EBF1C9', fg: '#321D53', fg_secondary: '#622A43' },
    dark: false,
    contrast: 12.5,
    aa: 'AAA',
  },
  {
    name: 'sands',
    label: 'Barren',
    colors: { bg: '#50462D', fg: '#ECA559', fg_secondary: '#B8AC7D' },
    dark: true,
    contrast: 4.47,
    aa: 'AA',
  },
  {
    name: 'default',
    label: 'Grain',
    colors: { bg: '#E6D6BC', fg: '#1B2154' },
    dark: false,
    contrast: 10.56,
    aa: 'AAA',
  },
  {
    name: 'default',
    label: 'Clay',
    colors: { bg: '#2B354D', fg: '#E8F4D4' },
    dark: true,
    contrast: 10.65,
    aa: 'AAA',
  },
  {
    name: 'violet',
    label: 'Scent',
    colors: { bg: '#E4D6EA', fg: '#251F50' },
    dark: false,
    contrast: 10.86,
    aa: 'AAA',
  },
  {
    name: 'violet',
    label: 'Noble',
    colors: { bg: '#503D81', fg: '#F7EAD2' },
    dark: true,
    contrast: 7.59,
    aa: 'AAA',
  },
  {
    name: 'grass',
    label: 'Cheese',
    colors: { bg: '#F3FEF1', fg: '#0A5FAE', fg_secondary: '#352C56' },
    dark: false,
    contrast: 6.21,
    aa: 'AA',
  },
  {
    name: 'grass',
    label: 'Portal',
    colors: { bg: '#326767', fg: '#F4E66B', fg_secondary: '#D4DCDB' },
    dark: true,
    contrast: 5,
    aa: 'AA',
  },
  {
    name: 'green',
    label: 'Moss',
    colors: { bg: '#C4EAC0', fg: '#38284B' },
    dark: false,
    contrast: 10.09,
    aa: 'AAA',
  },
  {
    name: 'green',
    label: 'Grove',
    colors: { bg: '#394649', fg: '#EFEECF' },
    dark: true,
    contrast: 8.29,
    aa: 'AAA',
  },
  {
    name: 'orange',
    label: 'Paw',
    colors: { bg: '#FAE4D3', fg: '#662530', fg_secondary: '#000136' },
    dark: false,
    contrast: 9.13,
    aa: 'AAA',
  },
  {
    name: 'orange',
    label: 'Crayon',
    colors: { bg: '#2E1202', fg: '#F9C679', fg_secondary: '#BEC6B8' },
    dark: true,
    contrast: 11.11,
    aa: 'AAA',
  },
]
